### ISSUE TITLE
How i can load NSString data by pointer with objc_str in pyobjus?

### ISSUE THREAD

**Issue by menangen** [kivy/pyobjus#10]
Can you help me and say how i can read NSString data by pointer into objc_str?

import ctypes
test_dylib = ctypes.cdll.LoadLibrary("test.dylib")
getUsername = test_dylib.getUsername
getUsername.restype = ctypes.c_char_p

getUsername() return pointer to NSString *function:

NSString *getUsername() {
    return @"abc";
}

And I need something like
print objc_str(*getUsername).UTF8String()
##

**Comment by Zen-CODE** [comment]
For an example. https://github.com/kivy/pyobjus/blob/master/examples/properties.py

If you find any specific bug or issue, please feel free to open another ticket.
