### ISSUE TITLE
Missing encoding for '@?'"

### ISSUE THREAD

**Issue by trivedigaurav** [kivy/pyobjus#14]
Trying to use MFMessageComposeViewController on iOS results in a missing encoding exception. The exception is raised on line 45 of the example code available here - https://gist.github.com/trivedigaurav/9d72ad632e493b2a0e6b#file-ios-sms-py-L45
##

**Comment by Zen-CODE** [comment]
That is an external example of which we cannot really verify the correctness. The info you provide does not directly indicate a problem with PyObjus as it could be a problem with the example.

I'll close this ticket for as there is too little information to do anything about. If you can demonstrate an issue in PyObjus, please open a new ticket with example code and an error log.

Thanks
