### ISSUE TITLE
Got dlopen error on Foundation

### ISSUE THREAD

**Issue by mrhdias** [kivy/pyobjus#22]
On OS X Yosemite with Xcode 7.2.1

I always got "Got dlopen error on Foundation" message

nano -w pyobjus-master/pyobjus/_runtime.h
https://github.com/kivy/pyobjus/blob/master/pyobjus/_runtime.h

"/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation"

But looking at my own system the initial /Groups/ is not a valid directory

**Comment by MounirHader** [comment]
Is this fixed? I have the same issue:

Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

And one error before that one:

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

The last directory does actually exist. Any ideas what causes the trouble?

Running Xcode 8.2 on OSX Sierra (10.12.1)

**Comment by heatherbaroody** [comment]
I realize this is closed and from a while ago but I am running into the same issue now and in following the merged issue, the solution isn't clear to me. @MounirHader did you ever figure it out? I am getting the exact messages but this time on Xcode 10.1, OSX High Sierra.
