### ISSUE TITLE
Adding Python 3.x support for PyOBJus

### ISSUE THREAD

**Issue by andong777** [kivy/pyobjus#28]
I can install it via pip on Python 3.x, but when I run the "Hello, world" example in the doc, it fails to execute  "from pyobjus import autoclass". On Python 2.x it works well. (I have tested on Python 2.7 and Python 3.5.)
 I also take a look at pyobjus.pyx. Though I don't know much about Cython, I notice that it supports Python 3.x. Therefore, I hope PyOBJus could support Python 3.x, to get access to the new Python features.
The previous discussion can be found [here](https://groups.google.com/forum/#!topic/kivy-users/9EM-GnOuShQ).
##

**Comment by tito** [comment]
Fixed last year
