### ISSUE TITLE
EXC_BAD_ACCESS code=1 address=0x1 when accepting multipeer connection

### ISSUE THREAD

**Issue by evbo** [kivy/pyobjus#34]
Hi,

I am simply using a `MCAdvertiserAssistant` and when a single connection is made, which ever device accepted the connection crashes with the following debug point in the code:

EXC_BAD_ACCESS code=1 address=0x1

```
  /* "pyobjus/pyobjus_conversions.pxi":164
 *     dprint("convert_to_cy_cls_instance: {0}".format(pr(ret_id)))
 *     cdef ObjcClassInstance cret
 *     bret = <bytes><char *>object_getClassName(ret_id)             # <<<<<<<<<<<<<<
 *     dprint(' - object_getClassName(f_result) =', bret)
 *     if bret == 'nil':
 */
  __pyx_t_1 = __Pyx_PyBytes_FromString(((char *)object_getClassName(__pyx_v_ret_id))); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[3]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = __pyx_t_1;
  __Pyx_INCREF(__pyx_t_2);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __pyx_v_bret = ((PyObject*)__pyx_t_2);
  __pyx_t_2 = 0;
```

If you decline the invitation this error does not occur (trivial case). I have tried running the zombie profiler, but this issue does not get caught as a zombie. It appears though that something is assumed stored in address "1", so I'm wondering if somewhere in pyobjus it is passing a hard-coded value of "1" rather than the pointer of correct type. 

Is anyone familiar with this issue? It is highly reproducible, for instance:

```
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.clock import Clock
from pyobjus import autoclass, protocol
from pyobjus.dylib_manager import load_framework
from datetime import datetime

from pyobjus import autoclass

load_framework('/System/Library/Frameworks/Foundation.framework')
load_framework('/System/Library/Frameworks/MultipeerConnectivity.framework')
NSString = autoclass('NSString')

NSUTF8StringEncoding = 4


class MCManager:

    def __init__(self):
        # get a random unique display name
        self.displayname = NSString.stringWithUTF8String_('pp' + str(datetime.now())[20:])
        self.serviceName = NSString.stringWithUTF8String_('chat-files')
        self.peerId = autoclass('MCPeerID').alloc().initWithDisplayName_(self.displayname)


        self.ad_session = autoclass('MCSession').alloc().initWithPeer_(self.peerId)
        self.ad_session.setDelegate_(self)

        self.browse_session = autoclass('MCSession').alloc().initWithPeer_(self.peerId)
        self.browse_session.setDelegate_(self)

        self.advertiser = autoclass('MCAdvertiserAssistant').alloc().initWithServiceType_discoveryInfo_session_(
            self.serviceName, None, self.ad_session)
        self.advertiser.start()

        self.browser = autoclass('MCNearbyServiceBrowser').alloc().initWithPeer_serviceType_(
            self.peerId, self.serviceName)
        self.browser.setDelegate_(self)
        self.browser.startBrowsingForPeers()

    @protocol('MCSessionDelegate')
    def session_peer_didChangeState_(self, session, peerID, state):
        pass

    @protocol('MCNearbyServiceBrowserDelegate')
    def browser_foundPeer_withDiscoveryInfo_(self, browser, peerId, discoveryInfo):
        print("found!", peerId, discoveryInfo)
        print str(self.peerId.hash())
        if self.peerId.hash() < peerId.hash():
            print("INVITING")
            browser.invitePeer_toSession_withContext_timeout_(peerId, self.browse_session, None, 30)
        else:
            print "awaiting invite instead"


class BasicWidget(Widget):
    mc = MCManager()


class BasicApp(App):
    def build(self):
        game = BasicWidget()
        return game


if __name__ == '__main__':
    BasicApp().run()

```
##

**Comment by evbo** [comment]
Short story is I was able to get MultiPeerConnectivity working, when invoked directly from a Kivy app.

Long story is I had to completely abandon my approach of maintaining delegates in python. The entire MultipeerConnectivity operation was instead coded entirely in objective-c (excellent reference on how to do so [here](http://www.appcoda.com/intro-multipeer-connectivity-framework-ios-programming/)).

In trying explain to myself why my approach originally failed, the most specific root cause I can conjecture is actual quite general and not very enlightening: 
> somewhere in my python memory management or method calls to objective-c I was totally messing things up.

To give a concrete example of how easy it is to mess up method calls, one of the methods [in the example I borrowed from](http://www.appcoda.com/intro-multipeer-connectivity-framework-ios-programming/) takes a `BOOL` value for whether or not the MultiPeer manager's `advertiser` should be started. I presumed I needed to send a `BOOL` literal, but it turns out this method, after being autoclassed, was expecting a string of length 1!!:

```
# this succeeds: self.mc.advertiseSelf_("1")
# but this fails:
self.mc.advertiseSelf_(ObjcBOOL(True))

# with:

   File "pyobjus/pyobjus.pyx", line 360, in pyobjus.pyobjus.ObjcMethod.__call__ (pyobjus/pyobjus.c:33558)
   File "pyobjus/pyobjus_conversions.pxi", line 496, in pyobjus.pyobjus.convert_py_arg_to_cy (pyobjus/pyobjus.c:26170)
 TypeError: ord() expected string of length 1, but pyobjus.pyobjus.ObjcBOOL found
```


So, this is no longer a problem for me, but I still feel this is an interesting case study. How could I have used python delegates and more carefully managed memory and more carefully performed method calls to the [objective-c library](http://www.appcoda.com/intro-multipeer-connectivity-framework-ios-programming/) used?

**Comment by hackalog** [comment]
FWIW, since applying PR#50, the coredump on accept appears to be happening here:

https://github.com/kivy/pyobjus/blob/9e92bf6754818b42dac6716b49c4799dc4c11117/pyobjus/pyobjus.pyx#L592

**Comment by Julian-O** [comment]
Closing as a support question.
