### ISSUE TITLE
dlopen error on Foundation

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/pyobjus#36]
On XCode 8/8.1 (on Sierra 10.12), pyobjus fails to load the foundation framework. This breaks all logs (nothing appears on the XCode console).

    Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): no suitable image found.  Did find:
	/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation: mach-o, but not built for iOS simulator

This used to work fine on 7.x (on Yosemite 10.10.5). The compile logs reveal no new errors during compile and libpyobjus.a builds and pyobjus functions still work on the deployed app. But logging is broken.

**Comment by hottwaj** [comment]
Have the same problem with a fresh setup on Sierra.

I also get no logs when running in simulation mode, but I do get something when running in debug mode on ipad...

The app breaks here in SDL:
![image](https://cloud.githubusercontent.com/assets/5629061/19984805/e42e70ae-a207-11e6-81e4-cb2836a3c94d.png)

Further up the call stack, here's the last call out from kivy:
![image](https://cloud.githubusercontent.com/assets/5629061/19985455/b1dbf9ac-a20a-11e6-8675-3f0d3398565e.png)

And I get this log output:

![image](https://cloud.githubusercontent.com/assets/5629061/19985357/3c7af0be-a20a-11e6-80d8-19166b465db6.png)

Not sure if this is even related to the dlopen Foundation issue or just a side effect?

Cheers

**Comment by Zen-CODE** [comment]
@Hottwaj. Interesting. I saw the icons for our project went dull, and when you removed them again showed a new icon. Try removing the reference to the OpenGLES.framework and re-adding it?

But you are getting logging. Our app shows none of the '[INFO  ]....' stuff in the console at all.

**Comment by Zen-CODE** [comment]
Discovered my logs start appearing if I remove these lines from 'main.m'. Will try and submit a PR for the fix soon.

        "# Fake redirection when we run the app without xcode\n" \
        "if 'CFLOG_FORCE_STDERR' not in environ:\n" \
        "    class fakestd(object):\n" \
        "        def write(self, *args, **kw): pass\n" \
        "        def flush(self, *args, **kw): pass\n" \
        "    sys.stdout = fakestd()\n" \
        "    sys.stderr = fakestd()\n" \

**Comment by Zen-CODE** [comment]
This only happens in the simulator, as the log message now indicates.
