### ISSUE TITLE
Print all class of Particular Framework

### ISSUE THREAD

**Issue by themontem** [kivy/pyobjus#37]
I want to print all class for IOKit Framework as I'm having problem in loading Objective C classes in pyobjus.

I want to import 
`#import <IOKit/ps/IOPowerSources.h>`
in pyobjus

**Comment by CyrielleAlbert** [comment]
I am also working with framework and looking for something similar. Even after loading the framework with load_framework, I can find a way to access classes.

**Comment by Zen-CODE** [comment]
Please post you request on the Kivy User Group forum or on discord. Issues are reserved for reporting demonstrable bugs in pyobjus or reasonable feature requests. Thanks
