### ISSUE TITLE
How to pass callback function from python to java or objective-c?

### ISSUE THREAD

**Issue by ghking1** [kivy/pyobjus#40]
now I can call a function, fun_native(callback_python),  in java or objective-c from python by pyjnius or pyobjus. 

but how can I pass and call a function, callback_python( ), write in python, from java or objective-c, when fun_native finished it's work?

**Comment by hackalog** [comment]
Objective-C (and pyobjus) uses delegates (and protocols) for this. See, e.g. https://github.com/kivy/pyobjus/blob/9e92bf6754818b42dac6716b49c4799dc4c11117/examples/delegate.py#L36-L38

**Comment by hackalog** [comment]
I'll close this for now. if you have further support questions, please feel free to ask them on discord: https://chat.kivy.org
