### ISSUE TITLE
string or bytes

### ISSUE THREAD

**Issue by michele-comitini** [kivy/pyobjus#48]
IMHO either b'' or '' everywhere, otherwise config.pxi is going to create the problem with ulng undefined again 
https://github.com/kivy/pyobjus/blob/9df65fffe34042ccfc9503295b7a0802c04d96da/setup.py#L13

**Comment by hackalog** [comment]
Was this addressed by https://github.com/kivy/pyobjus/commit/bbc06de28f69b7c8d94c539bbbb3789dabcbd8b5#diff-2a7e328574bb4ca83df55062b624e1bf (or the subsequent typo fix: https://github.com/kivy/pyobjus/commit/f84a58e9b301bffad508e13ccade6c0cdf79e2a3#diff-2a7e328574bb4ca83df55062b624e1bf)?

**Comment by michele-comitini** [comment]
I'd say that fixes it. Closing.
