### ISSUE TITLE
nameerror: name 'build_ext' is not defined during installation on linux

### ISSUE THREAD

**Issue by Testoviron-star** [kivy/pyobjus#68]
is there any way to solve that problem with installation on linux ?

`ERROR: Command errored out with exit status 1:
 command: /root/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lm35sz6r/pyobjus/setup.py'"'"'; _file__='"'"'/tmp/pip-install-lm35sz6r/pyobjus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file_);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, _file_, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lm35sz6r/pyobjus/pip-egg-info
     cwd: /tmp/pip-install-lm35sz6r/pyobjus/
Complete output (5 lines):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-install-lm35sz6r/pyobjus/setup.py", line 58, in <module>
    cmdclass={'build_ext': build_ext},
NameError: name 'build_ext' is not defined`

**Comment by tshirtman** [comment]
Did you install `cython` ? and made sure `setuptools` is a recent version ?

**Comment by Testoviron-star** [comment]
Yes. I have cython and latest setuptools.

**Comment by jayvdb** [comment]
It is caused by
https://github.com/kivy/pyobjus/commit/fbabc833890fc124c8e7703ef6650bad4b053e32

It should detect ios, but then fallback to Cython on any platform.

**Comment by jayvdb** [comment]
Then you will run into

> pyobjus/pyobjus.c:612:10: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory

**Comment by vrepo54** [comment]
I am facing exactly the same issue. Any idea of what could be done about it please?

**Comment by Julian-O** [comment]
There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).
